# Dictionary mapping YouTube links to anime titles
YOUTUBE_CLIPS_2025 = {
    "https://youtu.be/zkOYWw0u8as": "SAKAMOTO DAYS",
    "https://youtu.be/wOleNo7T6_4": "The Apothecary Diaries",
    "https://youtu.be/asyT-N1Ip70": "Danjon Meshi",
    "https://youtu.be/60_2zt9l3Yk": "Danjon Meshi",
    "https://youtu.be/S3v5gcwNeE8": "Moriarty the Patriot",
    "https://youtu.be/S0_qFgkDJxg": "Moriarty the Patriot",
    "https://youtu.be/iOrkj_MFXm8": "GOSICK",
    "https://youtu.be/_5WvUPHF5f8": "DEADMAN WONDERLAND",
    "https://youtu.be/oG4eu4HMtbo": "My Dress-Up Darling",
    "https://youtu.be/VekCU4YJiR8": "Banana Fish",
    "https://youtu.be/-jYqJCzZ8zs": "Banana Fish",
    "https://youtu.be/FWXkipC-vqs": "BanG Dream! Ave Mujica",
}

YOUTUBE_CLIPS = {
    "https://youtu.be/BYfAYpGxcNY": "Mekakucity Actors",
    "https://youtu.be/0hMz1J6EWWc": "KamiKatsu: Working for God in a Godless World",
    "https://youtu.be/Tt4_enX63K0": "Zom 100: Bucket List of the Dead",
    "https://youtu.be/tPeDnl1xBuk": "Black Butler",
    "https://youtu.be/Rm8UjBAS3cs": "Parasyte",
    "https://youtu.be/z9JZB08qy44": "The Apothecary Diaries",
    "https://youtu.be/29pmd1QiK-4": "The Apothecary Diaries",
    "https://youtu.be/PAcf55v6zqQ": "Oshi No Ko",
    "https://youtu.be/Wb-EeKm497o": "Haikyu!!",
    "https://youtu.be/qxoxR5KnqUk": "Detective Conan",
    "https://youtu.be/WRrZr6k7ZSU": "Demon Slayer",
    "https://youtu.be/XmpgKUcm2nI": "Nige Jozu no Wakagimi",
    "https://youtu.be/W4YKPLS7o8o": "How I Attended an All-Guy's Mixer",
    "https://youtu.be/_CraJ8654Bg": "BanG Dream! It's MyGO!!!!!",
    "https://youtu.be/IuSAC8ZDf1A": "WIND BREAKER",
    "https://youtu.be/ZZvIVRQ4E7I": "Shikanoko Nokonoko Koshitantan",
    "https://youtu.be/7GJOBkIgWHc": "Too Many Losing Heroines!",
    "https://youtu.be/a4na2opArGY": "Dandadan", 
    "https://youtu.be/KV8HGbACPzM": "Senpai Is an Otokonoko",
    "https://youtu.be/Bcy8yp6iYGI": "Oblivion Battery",
    "https://youtu.be/CFjI21M9wZs": "Kaiju No. 8",
    "https://youtu.be/PJirQlsWemk": "Skip and Loafer",
    "https://youtu.be/Za2FmwuIEwY": "The Dangers in My Heart",
    "https://youtu.be/j66_MdDhs-Y": "Let This Grieving Soul Retire!",
    "https://youtu.be/YDLafQ-Rg-k": "GIRLS BAND CRY",
    "https://youtu.be/4cTV5fWkqew": "Negative Positive Angler",
    "https://youtu.be/210R0ozmLwg": "Mashle: Magic and Muscles",
    "https://youtu.be/eZAocot63s8": "Orb: On the Movements of the Earth",
    "https://youtu.be/A0tKGpKOU4Y": "The Dangers in My Heart",
    "https://youtu.be/qU1XxZ37j7g": "BLUE LOCK",
    "https://youtu.be/pA-pzhQQFBA": "GIRLS BAND CRY",
    "https://youtu.be/ovW7yRi1iJ8": "Dandadan",
    "https://youtu.be/aiCMXJ4zKWA": "Kaiju No. 8",
}

YOUTUBE_CLIPS_S = {
    "https://youtu.be/3uHGkJbNkX0": "Mairimashita Iruma-kun",
    "https://youtu.be/DEAjG94U-Vk": "Mairimashita Iruma-kun",
    "https://youtu.be/RapvVfKmEUM": "Mairimashita Iruma-kun",
    "https://youtu.be/4GNTfA-seHY": "The Disastrous Life of Saiki K",
    "https://youtu.be/oc2rLPAJ06E": "The Disastrous Life of Saiki K",
    "https://youtu.be/aFe3srrhLdI": "Cells at Work!",
    "https://youtu.be/dnZBn4Mi3Z8": "Cells at Work! Code Black",
    "https://youtu.be/mQS_iWWp1sQ": "Assassination Classroom",   
    "https://youtu.be/QtsoCUPVW0E": "Assassination Classroom",
    "https://youtu.be/7_V7Cet4M_M": "Assassination Classroom",
    "https://youtu.be/Y9JPLPJLrlk": "Assassination Classroom",
    "https://youtu.be/tF4faMbs5oQ": "Dr.STONE",
    "https://youtu.be/SohCAjC-Npk": "Dr.STONE",
    "https://youtu.be/34wlhlQpidc": "Dr.STONE",
    "https://youtu.be/MEGBF9stDy0": "Dr.STONE",   
    "https://youtu.be/81H41vp96ag": "Dr.STONE",
    "https://youtu.be/TzZB-BOcpZY": "Dr.STONE",
    "https://youtu.be/v8bZVdTgXoY": "Jujutsu Kaisen",
    "https://youtu.be/8nNujr378EA": "Jujutsu Kaisen",
    "https://youtu.be/XS-N8KfZ5EU": "Haikyu!!",
    "https://youtu.be/WM-zyXoA7q8": "Haikyu!!",
    "https://youtu.be/araVYtu-RN4": "Haikyu!!",
    "https://youtu.be/7aNg8cV65Os": "Haikyu!!",
    "https://youtu.be/rBSfI10pXHM": "Haikyu!!",   
    "https://youtu.be/-ysq_MiwirU": "Haikyu!!",
    "https://youtu.be/HTh9MI8eqPo": "Haikyu!!",
    "https://youtu.be/Wb-EeKm497o": "Haikyu!!",
    "https://youtu.be/MbGj3zV3X8I": "Rascal Does Not Dream of a Dreaming Girl",
    "https://youtu.be/U_rWZK_8vUY": "SPY x FAMILY",
    "https://youtu.be/YOIJOJsUkUg": "SPY x FAMILY",
    "https://youtu.be/gz--GkzpAf8": "SPY x FAMILY",   
    "https://youtu.be/6PIDfpJWmek": "Hikaru no Go",
    "https://youtu.be/ekTuy8VOcug": "Hikaru no Go",
    "https://youtu.be/BrxhKLFHUu8": "Hikaru no Go",
    "https://youtu.be/jX-Ry1VxeDQ": "Odd Taxi",
    "https://youtu.be/6vRxlXHH4H8": "Kaguya-sama: Love Is War",   
    "https://youtu.be/4NEbSnuL6GA": "Kaguya-sama: Love Is War",
    "https://youtu.be/j3p6sXq_uUM": "Kaguya-sama: Love Is War",
    "https://youtu.be/XicdpSmxuT0": "Ya Boy Kongming!",
    "https://youtu.be/SzOWbrTG_kE": "Mashle: Magic and Muscles",
    "https://youtu.be/210R0ozmLwg": "Mashle: Magic and Muscles",
    "https://youtu.be/ZXB9OBHCiH8": "Detective Conan",
    "https://youtu.be/I59V9pjEOLI": "Mirai Nikki",
    "https://youtu.be/0_36iNzrEn0": "Mirai Nikki",
    "https://youtu.be/5Iv3Fi8eb7w": "BLUE LOCK",   
    "https://youtu.be/y8B6-Eot9iI": "BLUE LOCK",
    "https://youtu.be/PgBvV9ofjmA": "Oshi No Ko",
    "https://youtu.be/PAcf55v6zqQ": "Oshi No Ko",
    "https://youtu.be/z9JZB08qy44": "The Apothecary Diaries",
    "https://youtu.be/29pmd1QiK-4": "The Apothecary Diaries",
    "https://youtu.be/a4na2opArGY": "Dandadan", 
}

